stages:
  getdata:
    cmd: python3 src/main.py getdata --dataset_dir dataset
    deps:
    # - src/main.py
    - dataset/getdata.sh
    outs:
    - dataset/data
    - dataset/images

  preprocess:
    cmd: python3 src/main.py preprocess --dataset_dir dataset --graph_dir 
      out/graphs
    deps:
    # - src/main.py
    - src/preprocess.py
    - src/load_data.py
    - src/graph.py
    - src/gene_filtering.py
    outs:
    - out/graphs

  featurize:
    cmd: python3 src/main.py featurize --dataset_dir dataset --graph_dir 
      out/graphs --tensors_dir dataset/tensors
    deps:
    - src/main.py
    - src/preprocess.py
    - src/dataloader.py
    - src/load_data.py
    - src/graph.py
    - params.yaml
    outs:
    - dataset/tensors

  train:
    cmd: python3 src/main.py train --tensors_dir dataset/tensors --params_file 
      params.yaml
    deps:
    - src/main.py
    - src/train.py
    - src/model.py
    - src/mlflow_server.py
    - src/dataloader.py
    - params.yaml
    - dataset/tensors
    params:
    - train.learning_rate
    - train.num_epochs
    - train.batch_size
    - train.hidden1
    - train.hidden2
    - train.hidden3
    - train.label_smoothing
    outs:
    - models
    metrics:
    - metrics.json

  test:
    cmd: python3 src/main.py test --tensors_dir dataset/tensors --params_file 
      params.yaml
    deps:
    - dataset/tensors
    - params.yaml
    - src/dataloader.py
    - src/main.py
    - src/mlflow_server.py
    - src/model.py
    - src/train.py
