featurize:
  seed: 42
  pca_components: 55
train:
  learning_rate: 0.001
  num_epochs: 400
  weight_decay: 1e-5
  batch_size: 32
  hidden1: 208
  hidden2: 102
  hidden3: 40
  label_smoothing: 0.002
  early_stopping:
    patience: 40
tracking:
  port: 5000
  artifacts: "artifacts"
  log_dir: logs
  experiment_name: BrainLayerClassifier
  mlflow_pid: "mlflow.pid"
